project:
  type: website
  output-dir: docs

website:
  title: "y-sako's notes"
  navbar:
    right:
      - text: About
        file: about.qmd
      - icon: twitter
        href: https://twitter.com/nm_k_mn        
      - icon: github
        href: https://github.com/y-sako
format:
  html:
    theme: cosmo
    css: styles.css
