# version: '3'

services:
  quarto:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${COMPOSE_PROJECT_NAME}" # 任意のコンテナ名を.envで指定
    ports:
      - "${PORTS_NUM_RSTUDIO}:8787" # 任意のポート番号を.envで指定
    environment:
      - TZ=Asia/Tokyo
      - ROOT=TRUE
      - PASSWORD=password
      - DISABLE_AUTH=true
      - PYTHONUSERBASE=/home/rstudio/.pip
    volumes:
      - ./.rstudio/rstudio-prefs.json:/home/rstudio/.config/rstudio/rstudio-prefs.json
      - "${PATH_MNT}:/workspace"
      - renv:/home/rstudio/.cache/R/renv
      - pip:/home/rstudio/.pip
      # - TinyTeX:/home/rstudio/.TinyTeX
    tty: true
    stdin_open: true

volumes:
  renv:
    external: true
  pip:
    external: true